// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyBackendApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240606145828_ChangeIstEinzahlung")]
    partial class ChangeIstEinzahlung
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetApi.Models.BudgetSummaryEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Budget2023")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Budget2024")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IstEinzahlung")
                        .HasColumnType("bit");

                    b.Property<string>("Kategorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unterkategorie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Budgets");
                });
#pragma warning restore 612, 618
        }
    }
}
