// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyBackendApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetApi.Models.BudgetEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AB")
                        .HasColumnType("int");

                    b.Property<decimal>("BVA_2023")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BVA_2024")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DB1")
                        .HasColumnType("int");

                    b.Property<int?>("DB2")
                        .HasColumnType("int");

                    b.Property<string>("EV_FV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Erfolg_2022")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GB")
                        .HasColumnType("int");

                    b.Property<int?>("HH")
                        .HasColumnType("int");

                    b.Property<int?>("JAHR")
                        .HasColumnType("int");

                    b.Property<int>("KONTO")
                        .HasColumnType("int");

                    b.Property<string>("TEXT_KONTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEXT_VASTELLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UG")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Budgets");
                });
#pragma warning restore 612, 618
        }
    }
}
